//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BinhLuan()
        {
            this.NguoiDungs = new HashSet<NguoiDung>();
        }
    
        public int id { get; set; }
        public Nullable<int> ThucDon_id { get; set; }
        public Nullable<int> NguoiDung_id { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string User_Ten { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual ThucDon ThucDon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiDung> NguoiDungs { get; set; }
    }
}
