//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheDo
    {
        public int id { get; set; }
        public string HinhAnh { get; set; }
        public string CacBaiTap { get; set; }
        public string Link { get; set; }
        public string MotaCD { get; set; }
    }
}
