//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKV.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qlskEntities : DbContext
    {
        public qlskEntities()
            : base("name=qlskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BinhLuan> BinhLuans { get; set; }
        public virtual DbSet<CacMeoVat> CacMeoVats { get; set; }
        public virtual DbSet<CheDo> CheDoes { get; set; }
        public virtual DbSet<CuongDo> CuongDoes { get; set; }
        public virtual DbSet<KetQuaTDEE> KetQuaTDEEs { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<Table_GioiTinh> Table_GioiTinh { get; set; }
        public virtual DbSet<Table_Online> Table_Online { get; set; }
        public virtual DbSet<ThucDon> ThucDons { get; set; }
        public virtual DbSet<TinhTDEE> TinhTDEEs { get; set; }
    }
}
