//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThucDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThucDon()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.KetQuaTDEEs = new HashSet<KetQuaTDEE>();
        }
    
        public int id { get; set; }
        public string HinhAnh { get; set; }
        public string TenMonAn { get; set; }
        public string Loai { get; set; }
        public string MoTa { get; set; }
        public string NguyenLieu { get; set; }
        public string Buoc { get; set; }
        public string Mota2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KetQuaTDEE> KetQuaTDEEs { get; set; }
    }
}
