//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhTDEE
    {
        public int id { get; set; }
        public Nullable<double> CanNang { get; set; }
        public Nullable<double> ChieuCao { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public Nullable<int> CuongDoID { get; set; }
        public Nullable<int> GioiTinhID { get; set; }
    
        public virtual CuongDo CuongDo { get; set; }
        public virtual Table_GioiTinh Table_GioiTinh { get; set; }
    }
}
